name: gasec_mobile_app
description: Mobile app integrated with Gasec gas detector system.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_modular: 5.0.3
  flutter_phone_direct_caller: 2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Raster.png
    - assets/config.png
    - assets/logo.png